method=random
tiles=large_fern_top.png ft1 ft2 ft3 ft4 ft5
weights=1 1 1 1 1 1
matchTiles=large_fern_top_notint
biomes=snowy_taiga snowy_plains frozen_peaks frozen_river grove ice_spikes snowy_beach snowy_slopes jagged_peaks
heights=63-255