method=random
tiles=large_fern_bottom.png fb1 fb2 fb3 fb4 fb5
weights=1 1 1 1 1 1
matchTiles=large_fern_bottom_notint
biomes=snowy_taiga snowy_plains frozen_peaks frozen_river grove ice_spikes snowy_beach snowy_slopes jagged_peaks
heights=63-255