matchTiles=grass_notint
method=random
tiles=short_grass.png sg0 sg1 sg2 sg3 sg4 sg5 sg6
weights=1 1 1 1 1 1 1
biomes=snowy_taiga snowy_plains frozen_peaks frozen_river grove ice_spikes snowy_beach snowy_slopes jagged_peaks
heights=63-320
symmetry=all