method=random
tiles=tall_grass_top.png tg0 tg1 tg2 tg3 tg4 tg5 tg6 tg7
weights=1 1 1 1 1 1 1 1
symmetry=all
matchTiles=tall_grass_top_notint
biomes=snowy_taiga snowy_plains frozen_peaks frozen_river grove ice_spikes snowy_beach snowy_slopes jagged_peaks
heights=63-255